config/routes.rb
Rails.application.routes.draw do
  resources :people
  resources :rentals
  resources :puppies
  resources :advertisements, only: [:index]
  resources :shelters

  get "/logout", to: "sessions#logout", as: 'logout'

  root to: "main#index"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/advertisement.rb
class Advertisement < ApplicationRecord
    belongs_to :shelter
    belongs_to :puppy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cost.rb
class Cost < ApplicationRecord
    def self.rental_cost
        rand(20..50)
    end
  
end

app/models/person.rb
class Person < ApplicationRecord
    has_many :rentals
    has_many :puppies

    validates :name, :username, :email, :age, presence: true
    validates :username, :email, uniqueness: true

    has_secure_password

#    def has_any_rental
#         if self.rentals.count > 0
#             self.rentals.map {|rental| {rental.puppy.name}.join (", ")
#         else
#             "Looks like "
#         end
#    end
end

app/models/puppy.rb
class Puppy < ApplicationRecord
    has_many :advertisements
    has_many :rentals
    belongs_to :shelter
    belongs_to :person, optional: true
end

app/models/rental.rb
class Rental < ApplicationRecord
    belongs_to :puppy
    belongs_to :person

    validates :puppy_id, :person_id, :time, presence: true
    # validates :time, numericality: {greater_than_or_equal_to:1, less_than_or_equal_to: 24}

    def new_cost
        rand(20..50)
    end

end

app/models/shelter.rb
class Shelter < ApplicationRecord
    has_many :advertisements
    has_many :puppies
end

app/controllers/advertisements_controller.rb
class AdvertisementsController < ApplicationController

    def index
        @advertisements = Advertisement.all
    end

    # def show
    #     @advertisement = Advertisement.find(params[:id])
    # end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :find_current_person

    def find_current_person
        @current_person = Person.find_by(id: session[:person_id])
    end
end

app/controllers/main_controller.rb
class MainController  < ApplicationController
    def index
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController

    def show
        @person = Person.find(params[:id])
      
    end

    def new
        @person = Person.new
    end

    def create
        @person = Person.create(people_params)
        if @person.valid?
            session[:person_id] = @person.id
            redirect_to person_path(@person)
        else
            flash[:errors] = @person.errors.full_messages
            redirect_to new_person_path
        end
    end

    private

    def people_params
        params.require(:person).permit(:name, :age, :gender, :username, :email, :password)
    end

end

app/controllers/puppies_controller.rb
class PuppiesController < ApplicationController
    def index
        @puppies = Puppy.all
    end

    def show
        @puppy = Puppy.find(params[:id])
    end

    def update
        @puppy = Puppy.find(params[:id])
        @puppy.update(adoption:true, person_id:session["person_id"])
        redirect_to person_path(@puppy.person_id)
    end


end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
    def new
        @rental = Rental.new

        @puppies = Puppy.all
        render :new
    end

    def create
        params_hash = rental_params
        params_hash[:person_id] = session[:person_id]
        @rental = Rental.new(params_hash)
        
        if @rental.valid?
            @rental.save
            redirect_to person_path(@rental.person_id)
        else
            flash[:errors] = @rental.errors.full_messages
            redirect_to new_rental_path
        end
    end

     def destroy
        @rental = Rental.find(params[:id])
        @rental.destroy
        redirect_to person_path(@rental.person_id)
    
    end

    def update
        @rental = Rental.find(params[:id])
        @rental.update(complete:true)
        redirect_to person_path(@rental.person_id)
    end

    private

    def rental_params
        params.require(:rental).permit(:puppy_id, :person_id, :time)
    end

    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def logout
       session.delete(:person_id)
       redirect_to main_path
    end

    def new_login
        # render new
    end

    def create_login
        @person = Person.find_by(username: params[:session][:username])
    
        if @person && @person.authenticate(params[:session][:password])
          session[:person_id] = @person.id
          redirect_to person_path(@person)
        else
          flash[:error] = "Password or Username is incorrect"
          redirect_to new_login_path
        end 
      end 

end

app/controllers/shelters_controller.rb
class SheltersController < ApplicationController
    def index
        @shelters = Shelter.all
    end
end

app/helpers/advertisements_helper.rb
module AdvertisementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/puppies_helper.rb
module PuppiesHelper
end

app/helpers/rentals_helper.rb
module RentalsHelper
end

app/helpers/shelters_helper.rb
module SheltersHelper
end

app/views/advertisements/index.html.erb
<div class ="d-flex align-items-center justify-content-center">
<h1 style="margin: 50px 0;">All Puppies available for rental:</h1>
</div>

<div class="index-container">
    <% @advertisements.each do |ad|%>
        <%if ad.puppy.adoption == nil || ad.puppy.adoption == false %>

        <div class="index-card">
        <img class="index-img" src="<%= ad.puppy.image%>" alt="<%= ad.puppy.name %>"width="400" height="400">
        <p class="name"><%= link_to ad.puppy.name, puppy_path(ad.puppy.id)%></p>
        </div> 
        <% end %>
    <% end %>
</div>

app/views/main/index.html.erb
<div class ="d-flex align-items-center justify-content-center main_h1">
    <h1>Welcome to Pup A Day</h1>
</div>

<br>

<div class ="d-flex align-items-center justify-content-center">
  <h2> Rent or Adopt a Loveable Puppy from Local Shelters! 🐾</h2>
</div>

<br>

<div id="carouselExampleFade" class="carousel slide carousel-fade" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active" data-bs-interval="1400">
      <img src="https://images.unsplash.com/photo-1507146426996-ef05306b995a?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=1500&q=80" class="d-block w-50" alt="..." >
    </div>
    <div class="carousel-item" data-bs-interval="1400">
      <img src="https://images.unsplash.com/photo-1525253086316-d0c936c814f8?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1500&q=80" class="d-block w-50" alt="...">
    </div>
    <div class="carousel-item" data-bs-interval="1400">
      <img src="https://images.unsplash.com/photo-1576201836106-db1758fd1c97?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=2850&q=80" class="d-block w-50" alt="...">
    </div>
    <div class="carousel-item" data-bs-interval="1400">
      <img src="https://images.unsplash.com/photo-1530667912788-f976e8ee0bd5?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1500&q=80" class="d-block w-50" alt="...">
    </div>
  </div>
</div>

 <footer id="footer">
    <i class="fab fa-twitter fa-1x" aria-hidden="true"></i>
    <i class="fab fa-facebook-f fa-1x" aria-hidden="true"></i>
    <i class="fab fa-instagram fa-1x" aria-hidden="true"></i>
    <i class="fas fa-envelope fa-1x" aria-hidden="true"></i>
    <p class="Copyright">© Copyright 2021 PupADay </p>

  </footer>

app/views/people/new.html.erb
<h1 class="head">Sign Up Form</h1>

<% if flash[:errors]%>
    <% flash[:errors].each do |error|%>
        <div class="alert alert-danger"><%= error%></div>
    <% end %>
<%end%>

<section class="form" >
<%= form_for @person do |f|%>

    <div class="col-sm-3">
    <%=f.label :name, "Full Name: "%>  
    <%=f.text_field :name, class:"form-control"%></div>
    <br>

    <div class="col-sm-1">
    <%=f.label :age, "Age: "%> 
    <%=f.number_field :age, in:16..70, class:"form-control"%></div>
    <br>
    
  
    <div class="col-sm-1">
    <%=f.label :gender, "Gender: "%>
    <%=f.select :gender, ["Male", "Female"], class: "form-select"%>
    </div>
    <br>

    <div class="col-sm-3">
    <%=f.label :email, "Email: "%>  
    <%=f.text_field :email, class:"form-control"%></div>
    <br>
    
    <div class="col-sm-3">
    <%=f.label :username, "Username: "%>  
    <%=f.text_field :username, class:"form-control"%></div>
    <br>
    
    <div class="col-sm-3">
    <%=f.label :password, "Password: "%>  
    <%=f.password_field :password, class:"form-control"%></div>
    <br>
    
    <div class= "d-grid col-1">
    <%=f.submit "Signup", class:"btn btn-primary" %></div>
<%end%>
</section>


  

app/views/people/show.html.erb
<div id="welcome">
    <h1 class="welcome"> Welcome to <%=@person.name.titleize%>'s Profile</h1>
</div>

<div class = "show-container">
    <div class = "profile">
        <h3>Age: <%=@person.age%></h3>
        <h3>Gender: <%=@person.gender%></h3>
    </div>
    <div class = "upcoming">
        <h4> Your upcoming Puppy Rentals: </h4>
        <%if @person.rentals.count > 0 %>
        <div class="upcoming-container"> 
                <% @person.rentals.each do |rental|%>
                    <%if rental.complete == nil  && rental.puppy.adoption == nil|| rental.complete == false && rental.puppy.adoption == nil && rental.puppy.adoption == nil%>
                    <div class="upcoming-card"> 
                        <img class="index-img" src="<%= rental.puppy.image%>" alt="<%= rental.puppy.name %>"width="150" height="150">
                        <ul>
                                <li class="puppy_name"><%=link_to rental.puppy.name, puppy_path(rental.puppy.id)%><br>
                                    <p class="rental_time">Rental Time: <%= rental.time%></p>
                                </li>
                        </ul>
                   
                        <div class="button_cancel"><%= button_to "Cancel Rental", rental_path(rental.id), method: :delete,data:{confirm:"Sure?"}, class:"btn btn-outline-warning btn_cancel" %>
                        <%= button_to "Completed!", rental_path(rental.id), method: :patch, class: "btn btn-outline-secondary btn1" %></div>
                     </div>    
                    <%end%>
                <%end%>
                </div>

        <%else%>
            <p class="upcoming">Looks like you dont have any upcoming Puppy Rentals...</p> <br><br>
        <%end%>
    </div>

    <div class= "previous">
    
    <h4 class="h4"> Your Previous Puppy Rentals: </h4>
    <div class="previous-container">  
        <%if @person.rentals.count > 0 %>
                <%@person.rentals.each do |rental|%>
                    
                    <%if rental.complete == true && rental.puppy.adoption == nil%>
                        <div class="previous-card"> 
                            <img class="index-img" src="<%= rental.puppy.image%>" alt="<%= rental.puppy.name %>"width="150" height="150">
                            <ul>
                                <li class="adopt_puppy"> <%=link_to rental.puppy.name, puppy_path(rental.puppy.id)%><br>
                                </li>
                            </ul>
                            <%= button_to "Adopt this Puppy", puppy_path(rental.puppy.id), method: :patch, class: "btn btn-outline-secondary btn1"  %>
                        </div>
                    <%end%>
                <%end%>
               
                </div>
        <%else%>
            Looks like you dont have any completed Puppy Rentals... <br><br>
        <%end%>
        
    </div>

    <div class= "adopted">
        <h4> Members of your Pack: </h4>
        <% if @person.puppies.count > 0 %>
                <%@person.puppies.each do |puppy|%>
                    <%if puppy.adoption == true%>
                    <img class="index-img" src="<%= puppy.image%>" alt="<%= puppy.name %>"width="150" height="150">
                <ul>
                
                    <li><%=puppy.name%><br>
                    </li>
                </ul>
                    <%end%>
                <%end%> <br><br>
        <%else%>
            Looks like you havent adopted any puppies... <br><br>
        <%end%>
    </div>

</div>

app/views/puppies/index.html.erb
<h1>Puppies</h1>

app/views/puppies/show.html.erb
<h1 class="puppy_show">This is <%=@puppy.name%>!</h1>

<img class="show-picture" src="<%= @puppy.image %>" alt="<%= @puppy.name %>" width="280" height="280">
<section class="details">
<p><b>Name:</b> <%= @puppy.name%></p>
<p><b>Breed:</b> <%= @puppy.breed%></p>
<p><b>Age:</b> <%= @puppy.age%></p>
<p><b>Shelter Name:</b> <%= @puppy.shelter.name%></p>
<p><b>Shelter Location:</b> <%= @puppy.shelter.location%></p>
<p><b>Cute Fact about <%= @puppy.name%>:</b> <%= @puppy.cute_fact%></p>


<%flash[:puppy_id]=@puppy.id%>
<%flash[:puppy_name]=@puppy.name%>


<a class="btn btn-outline-secondary btn1" href="/rentals/new">Rent this cutie</a>
</section>

<footer id="footer">
    <i class="fab fa-twitter fa-1x" aria-hidden="true"></i>
    <i class="fab fa-facebook-f fa-1x" aria-hidden="true"></i>
    <i class="fab fa-instagram fa-1x" aria-hidden="true"></i>
    <i class="fas fa-envelope fa-1x" aria-hidden="true"></i>
    <p class="Copyright">© Copyright 2021 PupADay </p>

  </footer>

app/views/rentals/new.html.erb
<h1 class="head"> Lets rent a puppy! </h1>

<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <div class="alert alert-danger"><p><%= error %></p></div>
  <% end %>
<% end %>
<br>

<%= form_for @rental do |f|%>
      <h4>Puppy to Rent: <%=flash[:puppy_name]%></h4>
      <br><br>
      <%= f.label :cost, "Cost Per Hour: " %>
      $<%= @rental.new_cost %>
  

      <%= f.hidden_field :puppy_id, value: flash[:puppy_id] %>      
      <br><br><br>

      <div class="col-sm-2">
      <%= f.label :time, "Reserve a Time:" %>
      <%= f.number_field :time, in: 1..24, class:"form-control" %>
      <br><br>
     
<div class= "d-grid col-1">
    <%=f.submit "Submit", class:"btn btn-outline-secondary btn1" %></div>

<%end%>

app/views/shelters/index.html.erb
<h1 class ="d-flex align-items-center justify-content-center shelter_header"> Check Out These Success Stories!</h1>
<h2 class ="d-flex align-items-center justify-content-center shelter_header"> Here are the puppies that PupADay has helped find forever homes!</h2>



<% @shelters.each do |shelter|%>
    <%if shelter.puppies.count > 0 %>
    <%shelter.puppies.each do |puppy|%>
        <%if puppy.adoption == true%>
        
        <h3 class="main">    Shelter Name: <%=puppy.shelter.name%></h3>
        <img class="dog-img" src="<%=puppy.image%>" alt="adopted puppy" width="333" height="333">
        <ul><li class="main"><p><b> Puppy:</b> <%=puppy.name%></p></li></ul>
     
        <ul><li class="main"><p><b> Adopted By: </b><%=puppy.person.name %></p></li></ul>
        <hr>
        <%end%>
     <%end%>
     <%end%>
<%end%>